workflows:
  - name: code-quality
    image: python:3.10-bullseye
    steps:
      - name: Install and run flake 8
        run: |
          pip install flake8
          flake8
      - name: Install and run Black
        run: |
          pip install black
          black .
  - name: testing
    image: python:3.10-bullseye
    docker:
      - name: postgres
        image: postgres:latest
    steps: 
      - name: Wait for database to be ready
        run: echo "Mocking wait for db"
      - name: Install requirements
        run: echo "Mocking install requirements"
      - name: Run Django tests
        run: |
          cd src
          echo "running django tests"
