workflows:
  - name: code-quality
    image: python:3.10-bullseye
    steps: 
      - name: Flake 8
        run: echo "running flake 8"
      - name: Black
        run: echo "running black"
  - name: testing
    image: python:3.10-bullseye
    steps: 
      - name: Run Django tests
        run: |
          echo "running django tests"
          python3 manage.py test
