workflows:
  - name: testing
    image: python:3.10-bullseye
    docker:
      - name: postgres
        image: postgres:latest
    steps: 
      - name: Run tests
        run: |
          cd src
          python tests.py
