image: python:3.10-bullseye
workflows:
  - name: code-quality
    steps: 
      - name: Flake 8
        run: echo "running flake 8"
      - name: Blakc
        run: echo "running black"
  - name: testing
    steps: 
      - name: Run Django tests
        run: |
          echo "running django tests"
          python3 manage.py test
